#!/bin/sh

#if [ "$#" != 2 ]; then
#    echo "Usage: $0 SSH Login" >&2
#    exit 1
#fi

arg1=$1
arg2=$2

APIKEY="{YOUR API KEY}"
IDEN="{IDENTITY OF DEVICE SENDING TO}"

curl -u ${APIKEY}: "https://api.pushbullet.com/v2/pushes" \
-d type=note -d title="$1" -d body="$2" -d channel_tag={THE CHANNEL YOU WANT}
